service: suwon-scraper-lambda

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  memorySize: 2048
  timeout: 300
  environment:
    NODE_ENV: production
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
    binaryMediaTypes:
      - '*/*'

functions:
  scrape:
    handler: dist/handlers/scrape.handler
    events:
      - http:
          path: /scrape
          method: post
          cors: true
    layers:
      - {Ref: PlaywrightLambdaLayer}

layers:
  playwright:
    path: layer
    name: playwright-layer
    description: "Playwright Lambda Layer"
    compatibleRuntimes:
      - nodejs18.x

package:
  individually: true
  excludeDevDependencies: false
  patterns:
    - 'dist/**'
    - 'node_modules/**'
    - '!node_modules/.bin/**'
    - '!node_modules/.cache/**'
    - '!node_modules/@types/**'
    - '!.git/**'
    - '!.gitignore'
    - '!README.md'
    - '!tsconfig.json'
    - '!yarn.lock'
    - '!layer/**'
    - '!src/**'
    - '!.serverless/**'